### ISSUE TITLE
[QA] 로그인이 안된 상태에서 앱 실행이 안되는 이슈

### ISSUE THREAD

**Issue by KangJeee** [92-crew/dod-ios#46]
DataService.shared.fetchRemoteDB 함수가 로그인이 안된 상태에서 completion을 호출하지 않는 것 같음

**Comment by Juhyeoklee** [comment]
ㅁㅊ ㅋㅋㅋㅋㅋㅋㅋㅋ 
수정 해서 올렸습니다 ~!

**Comment by hunao3o** [comment]
ㅋㅋㅋ앤-하

**Comment by Juhyeoklee** [comment]
ㅋㅋㅋㅋㅋ @KangJeee  앤디님 !!
푸쉬 했습니다 확인해 주세요 !!

cc. @kkwang1223
